// src/lib/Search.svelte
<script lang="ts">
	export let inputValue: string = "";
  
	function isValidDomain(domain: string): boolean {
	  const domainRegex =
		/^(?!\-)([a-zA-Z0-9\-]{1,63})(?<!\-)(\.[a-zA-Z0-9\-]{1,63})*$/;
	  return domainRegex.test(domain);
	}
  </script>
  
  <div class="root">
	<form action={`/${inputValue}`} class="root-form" autocomplete="off">
	  <input
		class="form-domain"
		type="text"
		bind:value={inputValue}
		id="domain"
		placeholder="Enter a domain name without TLD"
	  />
	  <button
		class="form-submit"
		type="submit"
		disabled={!isValidDomain(inputValue)}
	  >
		<svg
		  xmlns="http://www.w3.org/2000/svg"
		  width="24"
		  height="24"
		  viewBox="0 0 24 24"
		>
		  <path
			fill="white"
			d="M19 18H6c-2.8 0-5-2.2-5-5 0-2.2 1.4-4 3.5-4.7.7-3.2 3.4-5.3 6.5-5.3 3.5 0 6.4 2.6 6.9 6 2.1.3 3.6 2.1 3.6 4.3 0 2.5-2 4.7-4.5 4.7z"
		  />
		</svg>
	  </button>
	</form>
  </div>
  
  <style>
	/* General styles */
	.root {
	  font-family: "Space Grotesk", sans-serif;
	  display: flex;
	  justify-content: center;
	  align-items: center;
	  margin-bottom: 2rem;
	}
  
	.root-form {
	  display: flex;
	  justify-content: center;
	  align-items: center;
	  gap: 1rem;
	  width: 100%;
	  max-width: 60vw;
	  margin: 0 auto;
	}
  
	/* Form input styles */
	.form-domain {
	  padding: 1.25rem;
	  border: 2px solid #ddd;
	  outline: none;
	  transition: all 0.3s ease;
	  box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1);
	  width: 70%;
	  font-size: 1.25rem;
	  background-color: white;
	  border-radius: 10px;
	}
  
	/* Form submit button */
	.form-submit {
	  display: flex;
	  justify-content: center;
	  align-items: center;
	  padding: 15px 25px;
	  background-color: #007bff;
	  border: none;
	  border-radius: 10px;
	  cursor: pointer;
	  box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1);
	  transition: background-color 0.3s ease;
	}
  
	.form-submit:hover {
	  background-color: #0056b3;
	}
  
	.form-submit:disabled {
	  background-color: grey;
	  cursor: not-allowed;
	}
  
	.form-submit:focus {
	  outline: none;
	  box-shadow: 0px 4px 6px rgba(0, 123, 255, 0.2);
	}
  
	.form-submit svg {
	  width: 24px;
	  height: 24px;
	}
  
	/* Desktop styles */
	@media (min-width: 769px) {
	  .root-form {
		flex-direction: row;
	  }
  
	  .form-domain {
		width: 30rem; /* Text input width as before */
	  }
  
	  .form-submit {
		width: auto; /* Small button beside input */
		padding: 15px 25px;
	  }
	}
  
	/* Mobile styles */
	@media (max-width: 768px) {
	  .root-form {
		flex-direction: column; /* Stack input and button vertically */
	  }
  
	  .form-domain {
		width: 100%; /* Full width for mobile */
	  }
  
	  .form-submit {
		width: 100%; /* Submit button matches input width */
	  }
	}
  </style>

// src/components/Search.tsx
import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';

function isValidDomain(domain: string): boolean {
	const domainRegex = /^(?!\-)([a-zA-Z0-9\-]{1,63})(?<!\-)(\.[a-zA-Z0-9\-]{1,63})*$/;
	return domainRegex.test(domain);
}

interface SearchProps {
	initialValue?: string;
}

export function Search({ initialValue = '' }: SearchProps) {
	const [value, setValue] = useState(initialValue);
	const navigate = useNavigate();

	useEffect(() => {
		setValue(initialValue);
	}, [initialValue]);

	const handleSubmit = (e: React.FormEvent) => {
		e.preventDefault();
		if (isValidDomain(value)) {
		navigate(`/${value}`);
		}
	};

	return (
		<div className="mb-8 flex items-center justify-center font-grotesk">
			<form
				onSubmit={handleSubmit}
				className="mx-auto flex w-full max-w-[60vw] flex-col items-center justify-center gap-4 md:flex-row"
				autoComplete="off"
			>
				<input
					className="w-full rounded-[10px] border-2 border-[#ddd] bg-white p-5 text-xl shadow-[0_4px_6px_rgba(0,0,0,0.1)] outline-none transition-all duration-300 md:w-[30rem]"
					type="text"
					value={value}
					onChange={(e) => setValue(e.target.value)}
					id="domain"
					placeholder="Enter a domain name without TLD"
				/>
				<button
					className="flex w-full cursor-pointer items-center justify-center rounded-[10px] border-none bg-primary px-6 py-[15px] shadow-[0_4px_6px_rgba(0,0,0,0.1)] transition-colors duration-300 hover:bg-primary-dark focus:outline-none focus:shadow-[0_4px_6px_rgba(0,123,255,0.2)] disabled:cursor-not-allowed disabled:bg-gray-500 md:w-auto"
					type="submit"
					disabled={!isValidDomain(value)}
					aria-label="Search domain availability"
				>
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
						<path
							fill="white"
							d="M19 18H6c-2.8 0-5-2.2-5-5 0-2.2 1.4-4 3.5-4.7.7-3.2 3.4-5.3 6.5-5.3 3.5 0 6.4 2.6 6.9 6 2.1.3 3.6 2.1 3.6 4.3 0 2.5-2 4.7-4.5 4.7z"
						/>
					</svg>
				</button>
			</form>
		</div>
	);
}
